#!/usr/bin/env python3
"""Clean-slate scrub of DERIVED pipeline state, preserving every paid artifact.

The import/enrich pipeline is incremental; repeated back-and-forth runs
accumulate stale derived state (merged people, directories, review decisions,
cluster indexes) that can fossilize wrong identities. This command resets the
pipeline to "fresh install + paid caches": everything derived is MOVED — never
deleted — into a timestamped backup directory OUTSIDE the repo, and everything
priced in tokens or API credits stays in place, keyed by stable identifiers so
the next full run (linkedin -> gmail -> messages -> deep-context) cache-hits.

PRESERVED (paid/LLM, stable keys):
  facts/*.jsonl                keyed by contact identity (candidate:email/phone)
  merge-verdicts.csv           cluster pair-judgment cache
  reconcile/verdicts.*         LinkedIn-judge verdicts, keyed by pub
  reconcile/deep-research/     Parallel results, keyed by parent slug
  import/linkedin/             source import + RapidAPI enrichment caches
  profile_cache_v2/            RapidAPI profile cache, keyed by pub
  owner.json + lookup          owner bio (RapidAPI)
  messages/, msgvault stores   raw local extracts
  logbook/, memory/, ingestion/  archives and wiring

SCRUBBED (derived; regenerates free on the next full run):
  merged/, directory.csv, overrides/ (review decisions incl. mirrors),
  import/gmail + import/messages*, discover/, search-index/,
  deep-context index/parents/dossiers/merge-candidates/raw/review state,
  reconcile summaries (applied.csv, summary.md, manifest.json), prefetch state.

Dry run by default. --apply moves and writes a manifest into the backup dir.

Created: 2026-07-18
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

# Directories/files to scrub, relative to .powerpacks. Globs allowed.
SCRUB = [
    ("network-import/merged", "fan-in output; rebuilt by the next fan-in"),
    ("network-import/directory.csv", "accumulated matcher state"),
    ("network-import/overrides", "review decisions + mirrors; mirrors re-derive from facts"),
    ("network-import/import/gmail", "regenerated by $import-gmail"),
    ("network-import/import/messages", "regenerated by $import-messages"),
    ("network-import/import/messages.bkup-*", "stale import backups"),
    ("network-import/discover", "staged discovery; regenerated from local stores"),
    ("search-index", "local search artifacts; rebuilt by indexing"),
    ("deep-context/index.json", "cluster/parents index; rebuilt by parents step"),
    ("deep-context/index.md", "derived index rendering"),
    ("deep-context/parents", "canonical parent stubs; rebuilt free"),
    ("deep-context/dossiers", "composed from facts; rebuilt free"),
    ("deep-context/merge-candidates.csv", "cluster proposals; re-proposed free (judgments cached)"),
    ("deep-context/merge-candidates.md", "cluster proposals rendering"),
    ("deep-context/raw", "ephemeral message bundles"),
    ("deep-context/review", "review-stage manifest"),
    ("deep-context/review-*.log", "review server logs"),
    ("deep-context/profile-prefetch", "prefetch manifest; cache itself is preserved"),
    ("deep-context/reconcile/manifest.json", "reconcile summary; regenerated"),
    ("deep-context/reconcile/summary.md", "reconcile summary; regenerated"),
    ("deep-context/reconcile/applied.csv", "reconcile summary; regenerated"),
    ("deep-context/reconcile/deep-research-sideline-*", "test-sidelined research dirs"),
]

# Explicitly preserved paths, printed for the operator. Nothing outside SCRUB is
# ever touched; this list exists to make the contract visible and auditable.
PRESERVE = [
    ("deep-context/facts", "OpenAI synthesis, keyed by contact identity"),
    ("deep-context/merge-verdicts.csv", "cluster pair-judgment cache"),
    ("deep-context/reconcile/verdicts.jsonl", "LinkedIn-judge verdicts"),
    ("deep-context/reconcile/verdicts.csv", "LinkedIn-judge verdicts (flat)"),
    ("deep-context/reconcile/deep-research", "Parallel research results"),
    ("deep-context/owner.json", "owner bio"),
    ("deep-context/owner_profile_lookup.json", "owner profile lookup"),
    ("network-import/import/linkedin", "LinkedIn source import + enrichment caches"),
    ("network-import/profile_cache_v2", "RapidAPI profile cache"),
    ("messages", "raw local message extracts + wacli store"),
    ("logbook", "verbatim conversation archive"),
    ("memory", "project-local agent memory"),
    ("ingestion", "linked-source wiring (accounts.json)"),
]


def path_size(path: Path) -> int:
    if path.is_file():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    total = 0
    for child in path.rglob("*"):
        if child.is_file():
            try:
                total += child.stat().st_size
            except OSError:
                pass
    return total


def fmt_size(n: int) -> str:
    value = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f}{unit}" if unit != "B" else f"{int(value)}B"
        value /= 1024
    return str(n)


def expand(root: Path, pattern: str) -> list[Path]:
    if any(ch in pattern for ch in "*?["):
        return sorted(root.glob(pattern))
    path = root / pattern
    return [path] if path.exists() else []


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=".powerpacks",
                    help="powerpacks state root (default .powerpacks)")
    ap.add_argument("--backup-dir", default="",
                    help="backup destination OUTSIDE the repo "
                         "(default ~/powerpacks-backups/clean-slate-<utc>)")
    ap.add_argument("--apply", action="store_true",
                    help="actually move; default is a dry run")
    args = ap.parse_args(argv)

    root = Path(args.root)
    if not root.exists():
        print(json.dumps({"status": "failed", "error": f"{root} not found"}))
        return 2
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = (Path(args.backup_dir).expanduser() if args.backup_dir
              else Path.home() / "powerpacks-backups" / f"clean-slate-{stamp}")
    try:
        if backup.resolve().is_relative_to(root.resolve()):
            print(json.dumps({"status": "failed",
                              "error": "backup dir must live OUTSIDE the state root"}))
            return 2
    except (OSError, RuntimeError):
        pass

    plan = []
    for pattern, why in SCRUB:
        for path in expand(root, pattern):
            plan.append({"path": str(path.relative_to(root)), "why": why,
                         "size_bytes": path_size(path)})
    kept = []
    for rel, why in PRESERVE:
        path = root / rel
        kept.append({"path": rel, "why": why, "exists": path.exists(),
                     "size_bytes": path_size(path) if path.exists() else 0})

    moved = []
    if args.apply:
        for entry in plan:
            src = root / entry["path"]
            dest = backup / entry["path"]
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dest))
            moved.append(entry["path"])
        if moved:
            manifest = {
                "primitive": "clean_slate",
                "scrubbed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "state_root": str(root.resolve()),
                "moved": moved,
                "preserved": [k["path"] for k in kept if k["exists"]],
                "restore": "move each path back from this directory into the state root",
            }
            backup.mkdir(parents=True, exist_ok=True)
            (backup / "clean-slate-manifest.json").write_text(
                json.dumps(manifest, indent=2), encoding="utf-8")

    result = {
        "primitive": "clean_slate",
        "status": "applied" if args.apply else "dry_run",
        "backup_dir": str(backup),
        "scrub": plan,
        "scrub_total_bytes": sum(e["size_bytes"] for e in plan),
        "preserve": kept,
        "preserve_total_bytes": sum(k["size_bytes"] for k in kept),
        "next": ["$setup (LinkedIn import + fan-in)", "$import-gmail",
                 "$import-messages", "$deep-context"],
    }
    print(json.dumps(result, indent=2))
    if not args.apply:
        print(f"dry run: {len(plan)} paths ({fmt_size(result['scrub_total_bytes'])}) "
              f"would move to {backup}; re-run with --apply", file=sys.stderr)
    else:
        print(f"moved {len(moved)} paths to {backup}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
