#!/usr/bin/env python3
"""Clean-slate scrub of DERIVED pipeline state, preserving every paid artifact.

The import/enrich pipeline is incremental; repeated back-and-forth runs
accumulate stale derived state (merged people, directories, review decisions,
cluster indexes) that can fossilize wrong identities. This command resets the
pipeline to "fresh install + paid caches": everything derived is MOVED — never
deleted — into a timestamped backup directory OUTSIDE the repo, and everything
priced in tokens or API credits stays in place, keyed by stable identifiers so
the next full run (linkedin -> gmail -> messages -> deep-context) cache-hits.

PRESERVED (paid/LLM/human, stable keys):
  facts/*.jsonl                keyed by contact identity (candidate:email/phone)
  deep-context.sqlite          human decisions + merge_verdicts paid cache
  reconcile/verdicts.*         LinkedIn-judge verdicts, keyed by pub
  reconcile/deep-research/     Parallel results, keyed by parent slug
  import/linkedin/             source import + RapidAPI enrichment caches
  profile_cache_v2/            RapidAPI profile cache, keyed by pub
  owner.json + lookup          owner bio (RapidAPI)
  messages/, msgvault stores   raw local extracts
  logbook/, memory/             archives

SCRUBBED (derived; regenerates free on the next full run):
  merged/, directory.csv, overrides/ (file mirrors; canonical human decisions stay in SQLite),
  import/gmail + import/messages*, discover/, search-index/,
  deep-context index/parents/dossiers/merge-candidates/raw/review state,
  reconcile summaries (applied.csv, summary.md, manifest.json), prefetch state.

Dry run by default. --apply moves and writes a manifest into the backup dir.

SCRUB and PRESERVE below are the whole policy: one row per path, first column
the path (globs allowed in SCRUB), second why it is in that column. The run
resolves each row against the state root into a frozen `ScrubTarget` /
`PreservedPath` and the payload renders from those.

Created: 2026-07-18
Changelog:
  2026-07-29 (setup style pass): the plan and preserve rows became the frozen
    `ScrubTarget` / `PreservedPath` instead of bare dicts built inline and
    re-indexed by string key three times; payload key order is unchanged (the
    result is printed with insertion order, not sorted).
  2026-07-23 (nuke accounts.json): dropped the ("ingestion", ...) PRESERVE entry.
    Nothing writes .powerpacks/ingestion/ anymore (the accounts.json linked-source
    registry was deleted), so there is no wiring left to preserve.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from packs.ingestion.primitives.deep_context.db.store import Db, DbMaintenance

# Directories/files to scrub, relative to .powerpacks. Globs allowed.
SCRUB = [
    ("network-import/merged", "fan-in output; rebuilt by the next fan-in"),
    ("network-import/directory.csv", "accumulated matcher state"),
    ("network-import/overrides", "file mirrors; canonical decisions remain in SQLite"),
    ("network-import/import/gmail", "regenerated by $import-gmail"),
    ("network-import/import/messages", "regenerated by $import-messages"),
    ("network-import/import/messages.bkup-*", "stale import backups"),
    ("network-import/discover", "staged discovery; regenerated from local stores"),
    ("search-index", "local search artifacts; rebuilt by indexing"),
    ("deep-context/index.md", "derived index rendering"),
    ("deep-context/parents", "canonical parent stubs; rebuilt free"),
    ("deep-context/dossiers", "composed from facts; rebuilt free"),
    ("deep-context/merge-candidates.csv", "cluster proposals; re-proposed free (judgments cached)"),
    ("deep-context/merge-candidates.md", "cluster proposals rendering"),
    ("deep-context/raw", "ephemeral message bundles"),
    ("deep-context/review", "review-stage manifest"),
    ("deep-context/review-*.log", "review server logs"),
    ("deep-context/profile-prefetch", "prefetch manifest; cache itself is preserved"),
    ("deep-context/reconcile/manifest.json", "reconcile summary; regenerated"),
    ("deep-context/reconcile/summary.md", "reconcile summary; regenerated"),
    ("deep-context/reconcile/applied.csv", "reconcile summary; regenerated"),
    ("deep-context/reconcile/deep-research-sideline-*", "test-sidelined research dirs"),
]

# Explicitly preserved paths, printed for the operator. Nothing outside SCRUB is
# ever touched; this list exists to make the contract visible and auditable.
PRESERVE = [
    ("deep-context/facts", "OpenAI synthesis, keyed by contact identity"),
    ("deep-context/deep-context.sqlite", "human decisions + paid merge verdicts"),
    ("deep-context/reconcile/verdicts.jsonl", "LinkedIn-judge verdicts"),
    ("deep-context/reconcile/verdicts.csv", "LinkedIn-judge verdicts (flat)"),
    ("deep-context/reconcile/deep-research", "Parallel research results"),
    ("deep-context/owner.json", "owner bio"),
    ("deep-context/owner_profile_lookup.json", "owner profile lookup"),
    ("network-import/import/linkedin", "LinkedIn source import + enrichment caches"),
    ("network-import/profile_cache_v2", "RapidAPI profile cache"),
    ("messages", "raw local message extracts + wacli store"),
    ("logbook", "verbatim conversation archive"),
    ("memory", "project-local agent memory"),
]


@dataclass(frozen=True)
class ScrubTarget:
    """One resolved path that will move to the backup dir, and why."""

    path: str
    why: str
    size_bytes: int

    def as_row(self) -> dict[str, Any]:
        return {"path": self.path, "why": self.why, "size_bytes": self.size_bytes}


@dataclass(frozen=True)
class PreservedPath:
    """One path the scrub must not touch, and whether it is actually there."""

    path: str
    why: str
    exists: bool
    size_bytes: int

    def as_row(self) -> dict[str, Any]:
        return {"path": self.path, "why": self.why, "exists": self.exists,
                "size_bytes": self.size_bytes}


def path_size(path: Path) -> int:
    if path.is_file():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    total = 0
    for child in path.rglob("*"):
        if child.is_file():
            try:
                total += child.stat().st_size
            except OSError:
                pass
    return total


def fmt_size(n: int) -> str:
    value = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.1f}{unit}" if unit != "B" else f"{int(value)}B"
        value /= 1024
    return str(n)


def expand(root: Path, pattern: str) -> list[Path]:
    if any(ch in pattern for ch in "*?["):
        return sorted(root.glob(pattern))
    path = root / pattern
    return [path] if path.exists() else []


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=".powerpacks",
                    help="powerpacks state root (default .powerpacks)")
    ap.add_argument("--backup-dir", default="",
                    help="backup destination OUTSIDE the repo "
                         "(default ~/powerpacks-backups/clean-slate-<utc>)")
    ap.add_argument("--apply", action="store_true",
                    help="actually move; default is a dry run")
    args = ap.parse_args(argv)

    root = Path(args.root)
    if not root.exists():
        print(json.dumps({"status": "failed", "error": f"{root} not found"}))
        return 2
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = (Path(args.backup_dir).expanduser() if args.backup_dir
              else Path.home() / "powerpacks-backups" / f"clean-slate-{stamp}")
    try:
        if backup.resolve().is_relative_to(root.resolve()):
            print(json.dumps({"status": "failed",
                              "error": "backup dir must live OUTSIDE the state root"}))
            return 2
    except (OSError, RuntimeError):
        pass

    plan = [
        ScrubTarget(path=str(path.relative_to(root)), why=why, size_bytes=path_size(path))
        for pattern, why in SCRUB
        for path in expand(root, pattern)
    ]
    kept = [
        PreservedPath(path=rel, why=why, exists=(root / rel).exists(),
                      size_bytes=path_size(root / rel) if (root / rel).exists() else 0)
        for rel, why in PRESERVE
    ]

    moved = []
    derived_reset = None
    sqlite_snapshot = None
    if args.apply:
        for target in plan:
            dest = backup / target.path
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(root / target.path), str(dest))
            moved.append(target.path)
        db_path = root / "deep-context/deep-context.sqlite"
        if db_path.exists():
            database = DbMaintenance(Db(db_path))
            snapshot_path = backup / "deep-context/deep-context.sqlite.before-clean-slate"
            database.backup_to(snapshot_path)
            sqlite_snapshot = str(snapshot_path.relative_to(backup))
            reset = database.reset_scrubbed_artifacts(tuple(
                (root / target.path).resolve() for target in plan
            ))
            derived_reset = {
                "artifacts": reset.artifacts,
                "facts": reset.facts,
                "research": reset.research,
                "guidance": reset.guidance,
            }
        if moved or sqlite_snapshot:
            manifest = {
                "primitive": "clean_slate",
                "scrubbed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "state_root": str(root.resolve()),
                "moved": moved,
                "preserved": [k.path for k in kept if k.exists],
                "sqlite_snapshot": sqlite_snapshot,
                "restore": (
                    "move each scrubbed path back; replace the canonical SQLite file "
                    "from sqlite_snapshot to restore its pre-reset derived rows"
                ),
            }
            backup.mkdir(parents=True, exist_ok=True)
            (backup / "clean-slate-manifest.json").write_text(
                json.dumps(manifest, indent=2), encoding="utf-8")

    result = {
        "primitive": "clean_slate",
        "status": "applied" if args.apply else "dry_run",
        "backup_dir": str(backup),
        "scrub": [target.as_row() for target in plan],
        "scrub_total_bytes": sum(target.size_bytes for target in plan),
        "preserve": [item.as_row() for item in kept],
        "preserve_total_bytes": sum(item.size_bytes for item in kept),
        "sqlite_derived_reset": derived_reset,
        "sqlite_snapshot": sqlite_snapshot,
        "next": ["$setup (LinkedIn import + fan-in)", "$import-gmail",
                 "$import-messages", "$deep-context"],
    }
    print(json.dumps(result, indent=2))
    if not args.apply:
        print(f"dry run: {len(plan)} paths ({fmt_size(result['scrub_total_bytes'])}) "
              f"would move to {backup}; re-run with --apply", file=sys.stderr)
    else:
        print(f"moved {len(moved)} paths to {backup}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
